// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/cart.proto

package cart

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Cart struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Items                []*Item  `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Cart) Reset()         { *m = Cart{} }
func (m *Cart) String() string { return proto.CompactTextString(m) }
func (*Cart) ProtoMessage()    {}
func (*Cart) Descriptor() ([]byte, []int) {
	return fileDescriptor_1520582f7a6ef1d6, []int{0}
}

func (m *Cart) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Cart.Unmarshal(m, b)
}
func (m *Cart) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Cart.Marshal(b, m, deterministic)
}
func (m *Cart) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Cart.Merge(m, src)
}
func (m *Cart) XXX_Size() int {
	return xxx_messageInfo_Cart.Size(m)
}
func (m *Cart) XXX_DiscardUnknown() {
	xxx_messageInfo_Cart.DiscardUnknown(m)
}

var xxx_messageInfo_Cart proto.InternalMessageInfo

func (m *Cart) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Cart) GetItems() []*Item {
	if m != nil {
		return m.Items
	}
	return nil
}

type Item struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Quantity             int32    `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Price                float32  `protobuf:"fixed32,4,opt,name=price,proto3" json:"price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Item) Reset()         { *m = Item{} }
func (m *Item) String() string { return proto.CompactTextString(m) }
func (*Item) ProtoMessage()    {}
func (*Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_1520582f7a6ef1d6, []int{1}
}

func (m *Item) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Item.Unmarshal(m, b)
}
func (m *Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Item.Marshal(b, m, deterministic)
}
func (m *Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Item.Merge(m, src)
}
func (m *Item) XXX_Size() int {
	return xxx_messageInfo_Item.Size(m)
}
func (m *Item) XXX_DiscardUnknown() {
	xxx_messageInfo_Item.DiscardUnknown(m)
}

var xxx_messageInfo_Item proto.InternalMessageInfo

func (m *Item) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Item) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Item) GetQuantity() int32 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

func (m *Item) GetPrice() float32 {
	if m != nil {
		return m.Price
	}
	return 0
}

type AddItemRequest struct {
	CartId               string   `protobuf:"bytes,1,opt,name=cart_id,json=cartId,proto3" json:"cart_id,omitempty"`
	Item                 *Item    `protobuf:"bytes,2,opt,name=item,proto3" json:"item,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddItemRequest) Reset()         { *m = AddItemRequest{} }
func (m *AddItemRequest) String() string { return proto.CompactTextString(m) }
func (*AddItemRequest) ProtoMessage()    {}
func (*AddItemRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1520582f7a6ef1d6, []int{2}
}

func (m *AddItemRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddItemRequest.Unmarshal(m, b)
}
func (m *AddItemRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddItemRequest.Marshal(b, m, deterministic)
}
func (m *AddItemRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddItemRequest.Merge(m, src)
}
func (m *AddItemRequest) XXX_Size() int {
	return xxx_messageInfo_AddItemRequest.Size(m)
}
func (m *AddItemRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddItemRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddItemRequest proto.InternalMessageInfo

func (m *AddItemRequest) GetCartId() string {
	if m != nil {
		return m.CartId
	}
	return ""
}

func (m *AddItemRequest) GetItem() *Item {
	if m != nil {
		return m.Item
	}
	return nil
}

type AddItemResponse struct {
	Cart                 *Cart    `protobuf:"bytes,1,opt,name=cart,proto3" json:"cart,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddItemResponse) Reset()         { *m = AddItemResponse{} }
func (m *AddItemResponse) String() string { return proto.CompactTextString(m) }
func (*AddItemResponse) ProtoMessage()    {}
func (*AddItemResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1520582f7a6ef1d6, []int{3}
}

func (m *AddItemResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddItemResponse.Unmarshal(m, b)
}
func (m *AddItemResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddItemResponse.Marshal(b, m, deterministic)
}
func (m *AddItemResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddItemResponse.Merge(m, src)
}
func (m *AddItemResponse) XXX_Size() int {
	return xxx_messageInfo_AddItemResponse.Size(m)
}
func (m *AddItemResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddItemResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddItemResponse proto.InternalMessageInfo

func (m *AddItemResponse) GetCart() *Cart {
	if m != nil {
		return m.Cart
	}
	return nil
}

type RemoveItemRequest struct {
	ItemId               string   `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	CartId               string   `protobuf:"bytes,2,opt,name=cart_id,json=cartId,proto3" json:"cart_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveItemRequest) Reset()         { *m = RemoveItemRequest{} }
func (m *RemoveItemRequest) String() string { return proto.CompactTextString(m) }
func (*RemoveItemRequest) ProtoMessage()    {}
func (*RemoveItemRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1520582f7a6ef1d6, []int{4}
}

func (m *RemoveItemRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveItemRequest.Unmarshal(m, b)
}
func (m *RemoveItemRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveItemRequest.Marshal(b, m, deterministic)
}
func (m *RemoveItemRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveItemRequest.Merge(m, src)
}
func (m *RemoveItemRequest) XXX_Size() int {
	return xxx_messageInfo_RemoveItemRequest.Size(m)
}
func (m *RemoveItemRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveItemRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveItemRequest proto.InternalMessageInfo

func (m *RemoveItemRequest) GetItemId() string {
	if m != nil {
		return m.ItemId
	}
	return ""
}

func (m *RemoveItemRequest) GetCartId() string {
	if m != nil {
		return m.CartId
	}
	return ""
}

type RemoveItemResponse struct {
	Cart                 *Cart    `protobuf:"bytes,1,opt,name=cart,proto3" json:"cart,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveItemResponse) Reset()         { *m = RemoveItemResponse{} }
func (m *RemoveItemResponse) String() string { return proto.CompactTextString(m) }
func (*RemoveItemResponse) ProtoMessage()    {}
func (*RemoveItemResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1520582f7a6ef1d6, []int{5}
}

func (m *RemoveItemResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveItemResponse.Unmarshal(m, b)
}
func (m *RemoveItemResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveItemResponse.Marshal(b, m, deterministic)
}
func (m *RemoveItemResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveItemResponse.Merge(m, src)
}
func (m *RemoveItemResponse) XXX_Size() int {
	return xxx_messageInfo_RemoveItemResponse.Size(m)
}
func (m *RemoveItemResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveItemResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveItemResponse proto.InternalMessageInfo

func (m *RemoveItemResponse) GetCart() *Cart {
	if m != nil {
		return m.Cart
	}
	return nil
}

type GetCartRequest struct {
	CartId               string   `protobuf:"bytes,1,opt,name=cart_id,json=cartId,proto3" json:"cart_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCartRequest) Reset()         { *m = GetCartRequest{} }
func (m *GetCartRequest) String() string { return proto.CompactTextString(m) }
func (*GetCartRequest) ProtoMessage()    {}
func (*GetCartRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1520582f7a6ef1d6, []int{6}
}

func (m *GetCartRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCartRequest.Unmarshal(m, b)
}
func (m *GetCartRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCartRequest.Marshal(b, m, deterministic)
}
func (m *GetCartRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCartRequest.Merge(m, src)
}
func (m *GetCartRequest) XXX_Size() int {
	return xxx_messageInfo_GetCartRequest.Size(m)
}
func (m *GetCartRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCartRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCartRequest proto.InternalMessageInfo

func (m *GetCartRequest) GetCartId() string {
	if m != nil {
		return m.CartId
	}
	return ""
}

type GetCartResponse struct {
	Cart                 *Cart    `protobuf:"bytes,1,opt,name=cart,proto3" json:"cart,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCartResponse) Reset()         { *m = GetCartResponse{} }
func (m *GetCartResponse) String() string { return proto.CompactTextString(m) }
func (*GetCartResponse) ProtoMessage()    {}
func (*GetCartResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1520582f7a6ef1d6, []int{7}
}

func (m *GetCartResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCartResponse.Unmarshal(m, b)
}
func (m *GetCartResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCartResponse.Marshal(b, m, deterministic)
}
func (m *GetCartResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCartResponse.Merge(m, src)
}
func (m *GetCartResponse) XXX_Size() int {
	return xxx_messageInfo_GetCartResponse.Size(m)
}
func (m *GetCartResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCartResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetCartResponse proto.InternalMessageInfo

func (m *GetCartResponse) GetCart() *Cart {
	if m != nil {
		return m.Cart
	}
	return nil
}

func init() {
	proto.RegisterType((*Cart)(nil), "cart.Cart")
	proto.RegisterType((*Item)(nil), "cart.Item")
	proto.RegisterType((*AddItemRequest)(nil), "cart.AddItemRequest")
	proto.RegisterType((*AddItemResponse)(nil), "cart.AddItemResponse")
	proto.RegisterType((*RemoveItemRequest)(nil), "cart.RemoveItemRequest")
	proto.RegisterType((*RemoveItemResponse)(nil), "cart.RemoveItemResponse")
	proto.RegisterType((*GetCartRequest)(nil), "cart.GetCartRequest")
	proto.RegisterType((*GetCartResponse)(nil), "cart.GetCartResponse")
}

func init() {
	proto.RegisterFile("proto/cart.proto", fileDescriptor_1520582f7a6ef1d6)
}

var fileDescriptor_1520582f7a6ef1d6 = []byte{
	// 333 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0xc1, 0x4e, 0xc2, 0x40,
	0x10, 0xa5, 0xa5, 0x80, 0x0e, 0x06, 0x75, 0x82, 0xa1, 0xe1, 0x60, 0x9a, 0x3d, 0xd5, 0x0b, 0x46,
	0xf4, 0xc0, 0x15, 0x8d, 0x31, 0xbd, 0xd6, 0x9b, 0x31, 0x31, 0x95, 0x9d, 0xc3, 0x1e, 0x4a, 0xa1,
	0x5d, 0x48, 0xfc, 0x3f, 0x3f, 0xcc, 0xcc, 0x2e, 0x2c, 0x05, 0x0e, 0x72, 0x9b, 0x37, 0x3b, 0xf3,
	0xde, 0x9b, 0x97, 0x85, 0xab, 0x45, 0x59, 0xe8, 0xe2, 0x7e, 0x96, 0x95, 0x7a, 0x64, 0x4a, 0x0c,
	0xb8, 0x16, 0x13, 0x08, 0x5e, 0xb2, 0x52, 0x63, 0x0f, 0x7c, 0x25, 0x43, 0x2f, 0xf2, 0xe2, 0xf3,
	0xd4, 0x57, 0x12, 0x23, 0x68, 0x29, 0x4d, 0x79, 0x15, 0xfa, 0x51, 0x33, 0xee, 0x8e, 0x61, 0x64,
	0x36, 0x13, 0x4d, 0x79, 0x6a, 0x1f, 0xc4, 0x27, 0x04, 0x0c, 0x8f, 0x36, 0x11, 0x82, 0x79, 0x96,
	0x53, 0xe8, 0x9b, 0x8e, 0xa9, 0x71, 0x08, 0x67, 0xcb, 0x55, 0x36, 0xd7, 0x4a, 0xff, 0x84, 0xcd,
	0xc8, 0x8b, 0x5b, 0xa9, 0xc3, 0xd8, 0x87, 0xd6, 0xa2, 0x54, 0x33, 0x0a, 0x83, 0xc8, 0x8b, 0xfd,
	0xd4, 0x02, 0x91, 0x40, 0x6f, 0x2a, 0xa5, 0xd1, 0xa3, 0xe5, 0x8a, 0x2a, 0x8d, 0x03, 0xe8, 0xb0,
	0x87, 0x2f, 0x27, 0xd6, 0x66, 0x98, 0x48, 0xbc, 0x85, 0x80, 0x1d, 0x19, 0xc1, 0x7d, 0xa7, 0xa6,
	0x2f, 0x1e, 0xe0, 0xd2, 0x51, 0x55, 0x8b, 0x62, 0x5e, 0x11, 0xaf, 0xf0, 0x94, 0x21, 0x72, 0x2b,
	0x9c, 0x43, 0x6a, 0x53, 0x79, 0x85, 0xeb, 0x94, 0xf2, 0x62, 0x4d, 0x07, 0x06, 0x98, 0xaf, 0x66,
	0x80, 0x61, 0x22, 0xeb, 0xce, 0xfc, 0xba, 0x33, 0xf1, 0x04, 0x58, 0xa7, 0x39, 0x51, 0xfc, 0x0e,
	0x7a, 0x6f, 0xa4, 0x4d, 0xe3, 0x9f, 0xd3, 0xf9, 0x34, 0x37, 0x7a, 0x1a, 0xfb, 0xf8, 0xd7, 0x83,
	0x2e, 0xc3, 0x77, 0x2a, 0xd7, 0x6a, 0x46, 0x38, 0x81, 0xce, 0x26, 0x1d, 0xec, 0xdb, 0xe1, 0xfd,
	0xdc, 0x87, 0x37, 0x07, 0x5d, 0xab, 0x23, 0x1a, 0x38, 0x05, 0xd8, 0x5d, 0x87, 0x03, 0x3b, 0x76,
	0x14, 0xdb, 0x30, 0x3c, 0x7e, 0x70, 0x14, 0x13, 0xe8, 0x6c, 0xfc, 0x6f, 0xc5, 0xf7, 0x2f, 0xdf,
	0x8a, 0x1f, 0x1c, 0x29, 0x1a, 0xcf, 0x17, 0x1f, 0xb0, 0xfb, 0xd1, 0xdf, 0x6d, 0x53, 0x3f, 0xfe,
	0x05, 0x00, 0x00, 0xff, 0xff, 0xcd, 0xce, 0x85, 0xd6, 0xe6, 0x02, 0x00, 0x00,
}
